### PR TITLE
Fixing update/commit musical chairs with forks.

### PR DESCRIPTION
**Pull request by steveehlert**

### CODE REVIEW

**Review by mfacorcoran — COMMENTED** [review]
Steven looks like you've re-defined the get_cif function (line 921-933) to return a fits HDU, which conflicts with another get_cif function which returns a pandas dataframe.  How about including a keyword flag to the get_cif function "return_hdu" (bool) which, if true, returns an HDU?

**Comment by steveehlert** [comment]
Hi Mike -

There was no get_cif() function external to the Caldb object, at least in the version I cloned. I mainly just put together the simplest and shortest version of a get_cif() function I could think of that would let the tests run. Feel free to replace it with anything else you may have in hand.

**Comment by mfacorcoran** [comment]
true – that seems like a reasonable thing to do; I’d prefer to keep the functionality the same between the pycaldb object and the external function

 

cheers

 

Mike

 

From: Steven Ehlert ***@***.***>
Reply-To: mfacorcoran/pycaldb ***@***.***>
Date: Friday, June 25, 2021 at 2:11 PM
To: mfacorcoran/pycaldb ***@***.***>
Cc: Michael Corcoran ***@***.***>, Comment ***@***.***>
Subject: Re: [mfacorcoran/pycaldb] Fixing update/commit musical chairs with forks. (#3)

 

Hi Mike -

There was no get_cif() function external to the PyCALDB object, at least in the version I cloned. I mainly just put together the simplest and shortest version of a get_cif() function I could think of that would let the tests run. Feel free to replace it with anything else you may have in hand.

**Comment by steveehlert** [comment]
I'm fine with the get_cif functions being consistent between the object-specific and general cases. Do you want me to try and code that up here? If so you will first need to provide what you had for the original version of it. It will also take a while to get the tests to behave because as of now they expect different outputs.

**Comment by mfacorcoran** [comment]
Hi Steven, 

How about I merge your current pull request and use that to modify/update my develop branch?

**Comment by steveehlert** [comment]
Sounds good. Let me know if/when you need some help or have some questions. 

Steven Ehlert

**Comment by mfacorcoran** [comment]
Hi Steven,

as you probably saw I merged your commit on the develop branch

**Pull request merged**
